# Generated by Django 4.2 on 2023-05-30 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamento", "0004_alter_orcamento_data_orcamento_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="data_orcamento",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 29, 21, 52, 20, 201423)
            ),
        ),
    ]
