# Generated by Django 4.2 on 2023-05-30 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orcamento", "0005_alter_orcamento_data_orcamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcamento",
            name="data_orcamento",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 29, 21, 53, 21, 234706)
            ),
        ),
        migrations.AlterField(
            model_name="orcamento",
            name="valor_orcamento",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=8, null=True
            ),
        ),
    ]
