# Generated by Django 4.2 on 2023-05-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0012_alter_estoqueproduto_id_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco', models.FloatField(default=0.0)),
                ('produto_vendido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto', to='produto.produto')),
            ],
        ),
    ]
