# Generated by Django 4.2 on 2023-05-18 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0002_venda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 5, 18, 20, 0, 42, 105903)
            ),
        ),
    ]
