# Generated by Django 4.2 on 2023-05-19 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0009_alter_venda_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 23, 58, 37, 198747)),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produtos_venda',
            field=models.ManyToManyField(blank=True, to='venda.produtovenda'),
        ),
    ]
