# Generated by Django 4.2 on 2023-10-08 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venda", "0031_alter_venda_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="produtos_venda",
            field=models.ManyToManyField(
                related_name="vendas", to="venda.produtovenda"
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="data",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 10, 8, 14, 50, 24, 446731)
            ),
        ),
    ]
