# Generated by Django 4.2 on 2023-10-08 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0039_alter_venda_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='preco_total',
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 15, 10, 38, 345054)),
        ),
    ]
