# Generated by Django 4.2 on 2023-05-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14)),
                ("telefone_1", models.CharField(max_length=15)),
                ("telefone_2", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("ativo_inativo", models.BooleanField(default=True)),
            ],
        ),
    ]
