# Generated by Django 4.2 on 2023-04-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="tipo_produto",
            field=models.CharField(max_length=50),
        ),
    ]
