# Generated by Django 4.2 on 2023-04-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
