# Generated by Django 4.2 on 2023-05-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produto", "0013_produto_quantidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="quantidade",
        ),
    ]
